#!/usr/bin/env python3
"""Render a p0_bench.py run into bench/BENCHMARKS.md.

`make bench` has called this file since P0 and it has never existed, so the target could
not complete: p0_bench.py wrote its JSON to the workstation and nothing turned it into
the table the brief asks for. Found by the STATUS re-audit, 24 Aug 2026.

    python3 scripts/bench_table.py bench/bench_<stamp>.json > bench/BENCHMARKS.md

The device RTC is unreliable (DECISIONS.md D-010), so the run is stamped from the host
via --stamp rather than from anything inside the JSON.
"""
import argparse
import json
import sys
from pathlib import Path


def g(d, *keys, default=None):
    """Nested get that tolerates a missing branch rather than raising mid-render."""
    for k in keys:
        if not isinstance(d, dict):
            return default
        d = d.get(k)
        if d is None:
            return default
    return d


def fmt(v, unit="", nd=1):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{nd}f}{unit}"
    return f"{v}{unit}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path")
    ap.add_argument("--stamp", default="",
                    help="host-side timestamp; the device clock is not trustworthy")
    args = ap.parse_args()

    data = json.loads(Path(args.json_path).read_text(encoding="utf-8"))
    meta = data.get("meta", {})
    rows = data.get("results", [])

    out = []
    out.append("# Benchmarks")
    out.append("")
    out.append(f"Device: **{meta.get('device', 'unknown')}**  ")
    out.append(f"nvpmodel conf: `{meta.get('nvpmodel_conf', '—')}`  ")
    out.append(f"Super profile active: **{meta.get('super_profile')}**  ")
    if args.stamp:
        out.append(f"Run: {args.stamp} (stamped from the host — see D-010)  ")
    out.append(f"Source: `{Path(args.json_path).name}`")
    out.append("")
    out.append("Generated by `scripts/bench_table.py`. Every column is measured on the "
               "device; none is derived from a datasheet.")
    out.append("")
    out.append("| Power mode | Model | tok/s (gen) | tok/s (prompt) | Load + minimal run | "
               "Peak RAM | Mean power | Peak GPU temp |")
    out.append("|---|---|---:|---:|---:|---:|---:|---:|")

    skipped = []
    for r in rows:
        mode = g(r, "mode", "name", default=str(g(r, "mode", "id", default="?")))
        model = r.get("model", "?")
        if r.get("skipped"):
            skipped.append(f"{mode} / {model}: {r['skipped']}")
            continue
        out.append("| {} | `{}` | {} | {} | {} | {} | {} | {} |".format(
            mode, model,
            fmt(g(r, "bench", "tg_tokens_per_second")),
            fmt(g(r, "bench", "pp_tokens_per_second")),
            fmt(g(r, "load", "load_plus_minimal_run_s"), "s"),
            fmt(g(r, "telemetry", "peak_ram_mb"), " MB", 0),
            fmt(g(r, "telemetry", "mean_power_w"), " W"),
            fmt(g(r, "telemetry", "peak_gpu_temp_c"), " °C"),
        ))

    if skipped:
        out.append("")
        out.append("## Skipped")
        out.append("")
        for s in skipped:
            out.append(f"- {s}")

    failed = [r for r in rows if r.get("load") and not g(r, "load", "ok", default=True)]
    if failed:
        out.append("")
        out.append("## Load failures")
        out.append("")
        out.append("A model that fails to load is reported, never omitted — an absent row "
                   "reads as 'not tested' rather than 'tested and broken'.")
        out.append("")
        for r in failed:
            out.append(f"- `{r.get('model')}` under {g(r, 'mode', 'name')}")

    print("\n".join(out))
    if not rows:
        print("\n> **No results in this run.**", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
